#!/usr/bin/env ruby

require_relative 'lib/environment'
require_relative 'lib/parse_arguments'
require_relative 'lib/interactions'
require_relative 'models/shelter'
require_relative 'models/breed'
require_relative 'models/role'

class FetchShelter
  include Interactions

  def initialize
    Environment.environment = "production"
  end

  def main
    zipcode = ARGV[0]
    if zipcode.nil?
      tell("You must enter a zipcode to search shelters")
      exit
    else
      shelters = Shelter.find_by_location(zipcode.to_i)
      shelter = give_options("Please select the shelter you would like stats on:", shelters)
      total_dogs = Shelter.calculate_total_dogs(shelter.petfinder_id)
      popular_breed = Shelter.calculate_popular_breed(shelter.petfinder_id)
      total_popular = popular_breed["Count(*)"]
      popular_breed = popular_breed["breed"]
      adoption_rate = Shelter.calculate_rate(shelter.petfinder_id, "X")
      pending_rate = Shelter.calculate_rate(shelter.petfinder_id, "P")
      holding_rate = Shelter.calculate_rate(shelter.petfinder_id, "H")
      puts
      tell(shelter.name)
      tell("Total dogs within shelter: #{total_dogs[0]}")
      tell("Most popular breed: #{popular_breed} (#{total_popular} total)")
      tell("Adoption Rate: #{adoption_rate}")
      tell("Pending Rate: #{pending_rate}")
      tell("Holding Rate: #{holding_rate}")
    end
  end
end

fetchshelter = FetchShelter.new()
fetchshelter.main()