#!/usr/bin/env ruby

require_relative 'lib/parse_arguments.rb'

command = ARGV[0]
options = ParseArguments.parse
options[:dog_name] = ARGV[1]
error_messages = ParseArguments.validate(options)

if error_messages.empty?
  puts "Theoretically creating: a dog named #{options[:dog_name]}, breed: #{options[:breed]}, shelter: #{options[:shelter]}, age: #{options[:age]} weight: #{options[:weight]} lbs. with an #{options[:status]} status for adoptable"
else
  puts error_messages
end