#!/usr/bin/env ruby

require_relative 'lib/environment'
require_relative 'lib/parse_arguments'
require_relative 'lib/interactions'

class FetchShelter
  include Interactions
  attr_reader :options

  def initialize
    @options = ParseArguments.parse
    Environment.environment = @options[:environment] || "production"
    @options.delete(:environment)
  end

  def main
    Environment.connect_to_database
    zipcode = options.delete(:command)
    if zipcode.nil?
      tell("You must enter a zipcode to search shelters")
      exit
    else
      print_shelter_stats(zipcode)
    end
  end

  def print_shelter_stats zipcode
    shelters = Shelter.where(location: zipcode.to_i)
    shelter = give_options("Please select the shelter you would like stats on:", shelters)
    puts shelter
    total_dogs = Shelter.calculate_total_dogs(shelter.petfinder_id)
    popular_breed = Shelter.calculate_popular_breed(shelter.petfinder_id)
    total_popular = popular_breed["total"]
    popular_breed = popular_breed["breed"]
    adoption_rate = Shelter.calculate_rate(shelter.petfinder_id, "X")
    pending_rate = Shelter.calculate_rate(shelter.petfinder_id, "P")
    holding_rate = Shelter.calculate_rate(shelter.petfinder_id, "H")
    puts
    tell(shelter.name)
    tell("Total dogs within shelter: #{total_dogs[0]}")
    tell("Most popular breed: #{popular_breed} (#{total_popular} total)")
    tell("Adoption Rate: #{adoption_rate}")
    tell("Pending Rate: #{pending_rate}")
    tell("Holding Rate: #{holding_rate}")
  end
end


fetchshelter = FetchShelter.new()
fetchshelter.main()